name: "Asynchronous Expo build"
description: "This action will upload a binary to a store using the Expo CLI, as well as remove the webhook that triggered it. Must use expo/expo-github-action@v5 prior to this action."

inputs:
  webhook_url:
    description: "The complete URL that was used to trigger this action. Usually the complete HTTPS path to your serverless function."
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
