name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - uses: EndBug/add-and-commit@v4
        with:
          tag: 'v2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
